### ISSUE TITLE
 ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.

### ISSUE THREAD

**Issue by gbardwell** [beyerleinf/ngx-dnd#49] opened 2019-02-12 00:52 UTC
6.0.1 version... (Note:  "@beyerleinf/ngx-dnd": "^6.0.0-preview3" works just fine.
It works with a simple "ng serve"...but not a production build.

When using "ng build --aot --prod"...

I get this error from your module:
ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.

[1] type { ngModule:
[1]    StaticSymbol {
[1]      filePath: 'C:/Users/Greg/WebstormProjects/saturn-funnels/node_modules/@beyerleinf/ngx-dnd/beyerleinf-ngx-dnd.d.ts',
[1]      name: 'DndModule',
[1]      members: [] },
[1]   providers:
[1]    [ undefined,
[1]      { provide: undefined, useFactory: undefined },
[1]      { provide: undefined, useFactory: undefined, deps: [Array] } ] }

**Comment by beyerleinf** [comment] 2019-02-12 21:28
Hi and thanks for creating an issue!

To be able to resolve your problem I nee a bit more info about your setup. Could you please run `ng version` in your projects' root directory and paste the output here? Also a small sample repo to reproduce your setup or a description on how to reproduce it would be helpful :)

**Comment by gbardwell** [comment] 2019-02-12 22:16
Angular CLI: 7.3.1
Node: 10.1.0
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.2.4
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.28.4

**Comment by beyerleinf** [comment] 2019-02-12 22:55
Thanks for providing more info! I have implemented a fix on the v7 branch and will publish the fix now. As you are using Angular 7 I would recommend using @beyerleinf/ngx-dnd@ng7. I will comment when I published the new Version. I will port the fixes to the v6 branch tomorrow.

**Comment by beyerleinf** [comment] 2019-02-12 23:08
Just published the new version. .forRoot() is not needed and not available anymore because I switched everything to the new DI process. Tell me if it works for you :)

**Comment by Serlegu** [comment] 2019-02-13 08:15
Hi,

I came across the same issue for version 6.01. Could you kindly have a look at it, please?

Thanks!

**Comment by beyerleinf** [comment] 2019-02-13 09:09
Like I said, I will port the fixes to v6 sometime today. I will close this issue once I fixed it in v6 as well.

**Comment by beyerleinf** [comment] 2019-02-13 22:27
I have now published the v6 Version. Feel free to comment if you have any more problems

**Closed as completed by beyerleinf** 2019-02-13 22:27 UTC
Labels: bug

**Comment by aaimaai** [comment] 2019-02-19 10:01
Hi, the current v6 branch solves this issue, thanks! Will this be available in version 6.0.2? When will this be released?
